"""Initial schema

Revision ID: 27659beb3b2f
Revises: 
Create Date: 2026-08-05 15:50:43.414420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27659beb3b2f'
down_revision = None
branch_labels = None
depends_on = None

# Postgres enum types are created implicitly by the create_table calls below,
# but drop_table does not remove them - they are schema objects in their own
# right, not part of any table. Left behind, the next upgrade fails on
# `CREATE TYPE role_enum` because the type already exists, so a downgrade
# makes the database impossible to migrate forward again.
#
# Enum.drop() is a no-op on backends without native enum types, so this stays
# correct on SQLite.
ENUM_TYPES = (
    'role_enum',
    'employment_type_enum',
    'employee_status_enum',
    'attendance_status_enum',
    'leave_type_enum',
    'leave_status_enum',
    'review_status_enum',
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('client', sa.String(length=120), nullable=True),
    sa.Column('site', sa.String(length=120), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('end_date IS NULL OR end_date >= start_date', name='ck_projects_date_order'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index('ix_projects_active', ['is_active'], unique=False)

    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_code', sa.String(length=12), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('employee', 'manager', 'hr_admin', name='role_enum'), nullable=False),
    sa.Column('employment_type', sa.Enum('full_time', 'part_time', 'contract', 'intern', name='employment_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('active', 'on_leave', 'terminated', name='employee_status_enum'), nullable=False),
    sa.Column('job_title', sa.String(length=120), nullable=False),
    sa.Column('join_date', sa.Date(), nullable=False),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('base_salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('country', sa.String(length=60), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('base_salary >= 0', name='ck_employees_salary_positive'),
    sa.CheckConstraint('exit_date IS NULL OR exit_date >= join_date', name='ck_employees_date_order'),
    sa.CheckConstraint('manager_id IS NULL OR manager_id <> id', name='ck_employees_self_manage'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index('ix_employees_department_status', ['department_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_employees_employee_code'), ['employee_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_employees_username'), ['username'], unique=True)

    op.create_table('attendance_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('clock_in', sa.Time(), nullable=True),
    sa.Column('clock_out', sa.Time(), nullable=True),
    sa.Column('status', sa.Enum('present', 'remote', 'absent', 'leave', 'holiday', name='attendance_status_enum'), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('clock_out IS NULL OR clock_in IS NULL OR clock_out > clock_in', name='ck_attendance_time_order'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'work_date', name='uq_attendance_employee_date')
    )
    with op.batch_alter_table('attendance_logs', schema=None) as batch_op:
        batch_op.create_index('ix_attendance_date_status', ['work_date', 'status'], unique=False)
        batch_op.create_index('ix_attendance_employee_date', ['employee_id', 'work_date'], unique=False)

    op.create_table('leave_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('leave_type', sa.Enum('annual', 'sick', 'unpaid', 'parental', 'bereavement', name='leave_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'cancelled', name='leave_status_enum'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('days', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('decided_by_id', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('(decided_by_id IS NULL) = (decided_at IS NULL)', name='ck_leave_decision_complete'),
    sa.CheckConstraint('days > 0', name='ck_leave_days_positive'),
    sa.CheckConstraint('end_date >= start_date', name='ck_leave_date_order'),
    sa.ForeignKeyConstraint(['decided_by_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.create_index('ix_leave_dates', ['start_date', 'end_date'], unique=False)
        batch_op.create_index('ix_leave_employee_status', ['employee_id', 'status'], unique=False)

    op.create_table('performance_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'acknowledged', name='review_status_enum'), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('improvements', sa.Text(), nullable=True),
    sa.Column('employee_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('period_end >= period_start', name='ck_review_period_order'),
    sa.CheckConstraint('rating IS NULL OR (rating >= 1 AND rating <= 5)', name='ck_review_rating_range'),
    sa.CheckConstraint('reviewer_id <> employee_id', name='ck_review_no_self_review'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'period_start', 'period_end', name='uq_review_employee_period')
    )
    with op.batch_alter_table('performance_reviews', schema=None) as batch_op:
        batch_op.create_index('ix_review_employee_status', ['employee_id', 'status'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('task_date', sa.Date(), nullable=False),
    sa.Column('hours', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('hours > 0 AND hours <= 24', name='ck_tasks_hours_range'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index('ix_tasks_employee_date', ['employee_id', 'task_date'], unique=False)
        batch_op.create_index('ix_tasks_project_date', ['project_id', 'task_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_tasks_project_date')
        batch_op.drop_index('ix_tasks_employee_date')

    op.drop_table('tasks')
    with op.batch_alter_table('performance_reviews', schema=None) as batch_op:
        batch_op.drop_index('ix_review_employee_status')

    op.drop_table('performance_reviews')
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_leave_employee_status')
        batch_op.drop_index('ix_leave_dates')

    op.drop_table('leave_requests')
    with op.batch_alter_table('attendance_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_attendance_employee_date')
        batch_op.drop_index('ix_attendance_date_status')

    op.drop_table('attendance_logs')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_username'))
        batch_op.drop_index(batch_op.f('ix_employees_employee_code'))
        batch_op.drop_index(batch_op.f('ix_employees_email'))
        batch_op.drop_index('ix_employees_department_status')

    op.drop_table('employees')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index('ix_projects_active')

    op.drop_table('projects')
    op.drop_table('departments')
    # ### end Alembic commands ###

    # Not auto-generated. See ENUM_TYPES above: without this the downgrade
    # leaves the types behind and the next upgrade cannot run.
    bind = op.get_bind()
    for name in ENUM_TYPES:
        sa.Enum(name=name).drop(bind, checkfirst=True)
